# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: emmanuelnk
subtitle: a coding blog
description:
author: Emmanuel
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://localhost:4000/
# url: https://emmanuelnk.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: true
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 0
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: serenity-theme
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/emmanuelnk/emmanuelnk.github.io.git
  branch: master

all_minifier: true

hljs:
  enable: true #true to enable the plugin
  line_number: frontend # add line_number in frontend or backend
  trim_indent: backend # trim the indent of code block to prettify output. backend or front-end (recommend)
  copy_code: true # show copy code in caption.
  label:
    left: Code
    right: ':'
    copy: copy

# misc
favicon: images/favicon.ico

# destacked Theme settings
dstkd:
  person_info:
    fullname: Emmanuel N Kyeyune
    country: uganda
    location: beijing, china
    intro: Hi there stranger,
    description: I'm <b>Emmanuel Nsubuga Kyeyune</b>. Software engineer, front/back-end dabbler (mostly react, node.js, python). Currently involved in the design and maintenance of cloud based applications. When I'm not working you can catch me watching indie films.<br><br>I try to write about anything and everything so feel free to look around!
    nav_img_url: /img/emmanuel_somber_bw_512.jpg #image @ right side of the navbar/popup (recommmended:512x512px)
  social_media_links:
    twitter: https://twitter.com/emmanuel_n_k
    github: https://github.com/emmanuelnk
    linkedin: https://www.linkedin.com/in/emmanuel-nsubuga-kyeyune
    medium: https://medium.com/@emmanuelkyeyune
  xkcd_images:
    - https://imgs.xkcd.com/comics/raptor_fences.png
    - https://imgs.xkcd.com/comics/containers.png
    - https://imgs.xkcd.com/comics/the_difference.png
    - https://imgs.xkcd.com/comics/when_you_assume.png
    - https://imgs.xkcd.com/comics/onboarding.png
    - https://imgs.xkcd.com/comics/old_accounts.png

# Disqus comments
disqus_shortname: emmanuelnk-github-io

# sitemap
sitemap:
    path: sitemap.xml
    tag: false
    category: false

#jsonContent
jsonContent:
  meta: true
  dateFormat: dddd, MMM D YYYY
  dafts: false
  file: all_content.json
  keywords: undefined
  pages:
    title: true
    slug: true
    date: true
    updated: true
    comments: true
    path: true
    link: true
    permalink: true
    excerpt: true
    keywords: false
    text: false
    raw: false
    content: true
    author: true
  posts:
    title: true
    slug: true
    date: true
    updated: true
    comments: false
    path: true
    link: true
    permalink: true
    excerpt: true
    keywords: false
    text: false
    raw: false
    content: true
    author: true
    categories: true
    tags: true



